// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // PKCE (supabase-js's default) requires the reset-password link to be
    // opened in the same browser/device that requested it — a common way
    // for "click reset, nothing happens" to occur (email opened elsewhere).
    // Implicit flow embeds the session directly in the link's URL fragment,
    // so it works regardless of device; that's also the format AuthContext's
    // PASSWORD_RECOVERY detection was built around.
    flowType: 'implicit',
  }
});